[package]
name = "aocsol"
authors = [ "HTGAzureX1212." ]
version = "0.0.0"
description = "Advent of Code Solutions"
edition = "2021"

[dependencies.aocfw]
path = "../aocfw"

[features]
year2015-day1 = []
